swagger: "2.0"
info:
  title: Golang API
  description: This is a sample API
  version: 1.0.0
host: localhost:3000
schemes:
  - http

paths:
  /api/version:
    get:
      tags:
        - "Api version"
      summary: Get API version
      description: Get the version of the API.
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              version:
                type: string
                example: "1.0.0"
